### PR TITLE
An Introduction to the RESTEasy Builtin Providers

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
@jamezp Could you please help to review this article when you have time? Thanks!

**Comment by jamezp** [comment]
I'm not too sure about this @liweinan. IMO blog posts should be about using API's. Those could be Jakarta REST API's or RESTEasy API's, but I don't think detailed implementation blogs help a user. 

This is also an area where I plan on significant changes so this could be out of date very quickly. See https://issues.redhat.com/browse/RESTEASY-2437 and https://issues.redhat.com/browse/RESTEASY-3108. The `ResteasyProviderFactory` is likely to be deprecated as well as loading the providers through a pseudo service file.

**Comment by liweinan** [comment]
> I'm not too sure about this @liweinan. IMO blog posts should be about using API's. Those could be Jakarta REST API's or RESTEasy API's, but I don't think detailed implementation blogs help a user.
> 
> This is also an area where I plan on significant changes so this could be out of date very quickly. See https://issues.redhat.com/browse/RESTEASY-2437 and https://issues.redhat.com/browse/RESTEASY-3108. The `ResteasyProviderFactory` is likely to be deprecated as well as loading the providers through a pseudo service file.

@jamezp Thanks for the info! I'll put this article into my own blog then and address the two issues about the future deprecation.

**Comment by jamezp** [comment]
Sounds good @liweinan. I do think it's a nice write up and makes sense. I hope it didn't come across as otherwise :) I just feel for resteasy.dev we should keep it with public API's :)

**Comment by liweinan** [comment]
> Sounds good @liweinan. I do think it's a nice write up and makes sense. I hope it didn't come across as otherwise :) I just feel for resteasy.dev we should keep it with public API's :)

yes sir!

**Pull request closed without merging**
